version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    env_file:
      - '.env'
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/uss-rides
    ports:
      - "3000:3000"
    env_file:
      - '.env'
    depends_on:
      - db